created styles folder, added colors, text styles.
calblueprint/dream-mobile pull request #6
Opened 2017-10-24 00:35 UTC by vanesng

+ created button components folder 
+ created teachers screens folder

2017-10-24 00:45 UTC, loischang requested changes

2017-10-24 00:45 UTC, loischang commented on screens/teachers/TeacherProfileEditScreen.js
> +import { styles } from '../../config/styles';
import from styles

2017-10-24 00:45 UTC, loischang commented on screens/teachers/TeacherProfileScreen.js
> +import { styles } from '../../config/styles';
import from styles

2017-10-24 00:45 UTC, loischang commented on styles/textStyles.js
> +export { textStyles };
nit: add new line at end of file

2017-10-24 00:45 UTC, loischang commented on styles/colors.js
> +export { colors };
nit: add new line at end of file

2017-10-24 01:04 UTC, loischang approved these changes

2017-10-24 01:04 UTC, loischang commented
LGTM  :D

2017-10-24 01:04 UTC, merged

2026-07-23 10:17 UTC, vivekp-toast commented on screens/teachers/TeacherProfileEditScreen.js
> +import { styles } from '../../config/styles';
Fixed in 2d974a8. The header bullet (line 8) and the revision note now both read TC-101–140.